import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import { cn } from '@/lib/utils'
import { ToastContainer, Flip } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css' // Certifique-se de importar os estilos do toastify

// import { Sidebar } from '@/components/sidebar'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Fabrica Prospera',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className={cn(
          'min-h-screen bg-background font-san',
          geistSans.variable,
          geistMono.variable,
          'antialiased'
        )}
      >
        {/* <Sidebar /> */}
        <ToastContainer
          position="top-right" // Define a posição dos toasts
          autoClose={4000} // Fecha automaticamente após 4 segundos
          hideProgressBar={false} // Mostra a barra de progresso
          newestOnTop={true} // Exibe os toasts mais recentes no topo
          closeOnClick // Fecha ao clicar
          rtl={false} // Direção da animação (direita para esquerda ou vice-versa)
          pauseOnFocusLoss // Pausa a contagem regressiva quando o navegador perde o foco
          draggable // Permite que o usuário arraste o toast
          pauseOnHover // Pausa a contagem regressiva quando o mouse está sobre o toast
          theme="colored" // Tema colorido para os toasts
          transition={Flip} // Animação do tipo Flip para a transição
          limit={1} // Limita a um toast por vez
        />
        {children}
      </body>
    </html>
  )
}
